'use client';
import { RecoilRoot } from 'recoil';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import GlobalStyle from '../styles/globalStyle';
import '../styles/fonts/font.css';
import { ChakraProvider } from '@chakra-ui/react';

const inter = Inter({ subsets: ['latin'] });

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <GlobalStyle />
      <RecoilRoot>
        <html lang="en">
          <body className={inter.className}>{children}</body>
        </html>
      </RecoilRoot>
    </>
  );

