'use client';
import { RecoilRoot } from 'recoil';
import { Inter } from 'next/font/google';
import GlobalStyle from '../styles/globalStyle';
import '../styles/fonts/font.css';
import { Registry } from './registry';
import BgmPlayer from './home/page';
import { Header } from '@components/Header';

const inter = Inter({ subsets: ['latin'] });

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <RecoilRoot>
        <html lang="en">
          <body className={inter.className}>
            <Registry>
              <GlobalStyle />
              {children}
              <BgmPlayer />
            </Registry>
          </body>
        </html>
      </RecoilRoot>
    </>
  );
}
